version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: stock-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=stockdb
    networks:
      - stock-network

  stockbackend:
    build:
      context: ./StockBackend
      dockerfile: Dockerfile
    container_name: stock-backend
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - stock-network

volumes:
  mongo-data:

networks:
  stock-network:
    driver: bridge