version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: stock-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=stockdb

volumes:
  mongo-data: