name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  # Step 1: Build & Push Docker Image for Backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t stock-backend -f stock-backend/Dockerfile stock-backend

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag stock-backend:latest qubegubble/stock-backend:latest
          docker push qubegubble/stock-backend:latest
  # TODO : Deploy Backend to Server

  # Step 2: Build & Deploy Documentation to GitHub Pages
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Asciidoctor
        run: sudo apt-get install asciidoctor

      - name: Build Documentation
        run: asciidoctor -D doc/output doc/index.adoc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: doc/output