name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  # Step 1: Build & Push Docker Image for Backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t stock-backend -f stock-backend/Dockerfile stock-backend

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag stock-backend:latest qubegubble/stock-backend:latest
          docker push qubegubble/stock-backend:latest
  # TODO : Deploy Backend to Server

  # Step 2: Build & Push Docker Image for Frontend
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd dashboard && npm install

      - name: Build Dashboard
        run: cd dashboard && npm run build -- --configuration=production --base-href /stock_market_dashboard/dashboard/

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dashboard/dist/dashboard